In [2]:
import tensorflow as tf
print(('your tensorflow version: {0}').format(tf.__version__))

your tensorflow version: 2.7.0


Tensor are defined by a unit of dimensionality called as rank.
>scalar=300 with rank 0.
>vector =[1,2,3] with rank 1.
>matrix=[[1,2],[3,4]] with rank 2.
>Tensor=[[[1],[2],[3]]]  with rank 3

| example    | Rank                       |
| :-------- | :------------------------- |
| `scalar=100` | `` | **Required**. Your API key |

In [3]:
x=tf.constant([1,2,3,4,5])
y=tf.constant([6,7,8,9,10])

In [4]:
a=tf.add(x,y)

In [5]:
print(a)

tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)


In [6]:
%load_ext tensorboard

In [7]:
tensor= tf.ones(shape=[2,3])

In [8]:
print(tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [9]:
tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

AttributeError: module 'tensorflow' has no attribute 'Transpose'