#### Creating a constant tensor from a tensor-like object, Tensorflow 2.x

 tf.constant(
    value, dtype=None, shape=None, name='Const'
) 

In [ ]:
import tensorflow as tf

In [4]:
#tensor version

tf.__version__

'2.7.0'

In [5]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [6]:
tf.config.list_physical_devices('GPU')

[]

In [10]:
#create integer constant
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [11]:
tf.constant('tensorflow')

<tf.Tensor: shape=(), dtype=string, numpy=b'tensorflow'>

In [14]:
# constant 1-D Tensor from a python list.
tf.constant([1,2,3,4])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [15]:
tf.constant(0, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [17]:
#tf variable
tf.Variable([0,0])

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([0, 0])>