## NumPy 
> numpy is the fundamental package for scientific computing in python.
> numpy is a python package which stands for numerical python consisting of multidimensional array .

> ndarray = n dimentional array

In [2]:
import numpy
import numpy as np

In [3]:
arr = numpy.array([1,2,3,4,5,6])

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
print(arr)

[1 2 3 4 5 6]


In [6]:
np.__version__

'1.21.5'

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.shape

(9,)

In [11]:
# 0 dimension array are scalars in 0-D there is no need of square bracket[]

arr = np.array(5)

In [12]:
# 1 dimensional array or uni-dimensional in 1-d single square brackets are used


arr= np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [13]:
# 2 dimensional arrays are matrices where 2 square bracket[[]] is used

arr= np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# 3 dimensional array [[[]]]
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [15]:
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [16]:
# An array can have any number of dimensions.

In [17]:
#accessing array

arr1 =np.array([1,2,3,4,5,6,7,8,9])

print(arr1[1:7])

[2 3 4 5 6 7]


In [18]:
print(arr1[4:])

[5 6 7 8 9]


In [19]:
print(arr1[:4])

[1 2 3 4]


In [20]:
# ndmin is n- dimensional array

arr2 = np.array([1,2,3,4], ndmin=4)

In [21]:
arr2

array([[[[1, 2, 3, 4]]]])

In [22]:
arr2.shape

(1, 1, 1, 4)

### Reshape 

In [24]:
# reshape from 1-d to 2-d 

import numpy as np

arr3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

arr4 = arr3.reshape(4,3)


In [26]:
arr4  # 1d to 2d conversion

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
# 1d to 3d 

arr5 = arr3.reshape(2,3,2)

arr5

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [29]:
nwarray = np.array([1,2,3,4,5,6,7,8])

In [31]:
arrnw = nwarray.reshape(2,4)

In [32]:
arrnw

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
print(nwarray.reshape(2,4).base)  # base return to original array

[1 2 3 4 5 6 7 8]
